service: default

runtime: go113
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.75
  min_instances: 0
  max_instances: 2
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_concurrent_requests: 20

handlers:
- url: /.*
  script: auto

